### ISSUE TITLE
python library versions ?

### ISSUE THREAD

**Issue by cramraj8** [sharad461/nepali-translator#3]
What are the python, pytorch, fairseq versions that you used to run ?

**Comment by sharad461** [comment]
While I didn't make a note of the versions while training, these versions were compatible for inference as of 2020:
`fairseq-0.9.0` `portalocker-2.0.0` `sacrebleu-1.4.14` `sacremoses-0.0.43` `sentencepiece-0.1.91`

As a last resort, you can search respective versions available around July 2019.
