### ISSUE TITLE
Anyway to convert your en source into csv file without losing the format?

### ISSUE THREAD

**Issue by ShikharGhimire** [sharad461/nepali-translator#4]
I have been trying to convert your source data from .en or .np file into .csv file without losing the format. I tried to do it by converting into excel and eventually into .csv file but the format gets all over the place. Any tips? Please let me know. Thank you

**Comment by sharad461** [comment]
Do you mean a csv file with, say, three columns id, eng, nep such that in every row the eng sentence and the nep sentence are mapped parallelly? This should be pretty straight forward if you use pandas.
