### ISSUE TITLE
Data cleaning and corpus

### ISSUE THREAD

**Issue by stha-prashant** [sharad461/nepali-translator#6]
Hello I couldn't find this in the readme, and I have a few questions.
1. are the train.en and train.ne files in the collected folder of the corpus after or before data cleaning?
2. which of the corpus was used in the paper? corpus.zip or corpus_NOV2019.tar.gz? both seem to have fewer sentences than reported in the paper. For the second one, the files inside collected have 1780248 sentences whereas the paper mentions about 1810000 sentences.

Thanks.

**Comment by sharad461** [comment]
1. After cleaning. Those are the final versions.
2. The earlier corpus.zip was collected for a college project (the report). The latter corpus_NOV2019.tar.gz is the definitive collection which was used in the paper.
