### ISSUE TITLE
what version of python was used ?

### ISSUE THREAD

**Issue by KrishnaMBhattarai** [sharad461/nepali-translator#7]
hello,

I was attempting to install the requirements described in the readme with python 3.11 but it throws a bunch of compatibility errors. What version of python is expected for this project? 3.7? 3.8? 3.9? which one? 

also what version of torch is required?

**Comment by KrishnaMBhattarai** [comment]
also having trouble installing torch-1.3.0. Is it possible to upgrade the version of these packages and get this repo in a good shape so we can make some progress?

**Comment by sharad461** [comment]
Hi, thanks for your interest. 

I probably will not manage to maintain this project. Additionally, I consider the data and techniques here more worthy than the translation system itself. You can install the python version and packages as of late 2019: `python-3.8` `fairseq-0.9.0` `portalocker-2.0.0` `sacrebleu-1.4.14` `sacremoses-0.0.43` `sentencepiece-0.1.91`. Torch 1.3.0 should be fine. 

If you want to see the system/models at work you can always check https://translation.ilprl.ku.edu.np/.

**Comment by KrishnaMBhattarai** [comment]
Thank you for your answer and more details!
